on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jiro4989/setup-nim-action@v1
      - uses: juancarlospaco/nimlint-action@main
      # Uncomment this to commit all Nimlint fixes back to the Git repo.
      # - name: Commit Nimlint Fixes
      #   uses: EndBug/add-and-commit@v5  # https://github.com/EndBug/add-and-commit
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
